"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.x.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": "aws-1-ap-south-1.pooler.supabase.com",
        "PORT": "6543",
        "NAME": "postgres",
        "USER": "postgres.vzmbwobdlddxzgqfhnsh",
        "PASSWORD": "shaishavroot19",
        "OPTIONS": {"sslmode": "require"},
    }
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-this-to-a-unique-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["app.root19.com","34.14.174.152", "127.0.0.1", "localhost"]

CSRF_TRUSTED_ORIGINS = [
    "http://app.root19.com",
    "https://app.root19.com"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'root_19',
    'main'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.StaticMediaCacheMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'root_19.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # You can add your template directories inside the list below
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.streak_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'root_19.wsgi.application'


# Database
# Configure PostgreSQL (Supabase) as the default database. The credentials are
# hard-coded for now but should be moved to environment variables in
# production.

DB_HOST = 'db.vzmbwobdlddxzgqfhnsh.supabase.co'
DB_PORT = 5432
DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASSWORD = 'shaishavroot19'
user="postgres.vzmbwobdlddxzgqfhnsh"
password="shaishavroot19" 
host="aws-1-ap-south-1.pooler.supabase.com"
port="6543"
dbname="postgres"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.vzmbwobdlddxzgqfhnsh',
        'PASSWORD': 'shaishavroot19',
        'HOST': 'aws-1-ap-south-1.pooler.supabase.com',
        'PORT': 6543,
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}
# Seconds to wait when opening the DB connection (used by main/db.py).
DB_CONNECT_TIMEOUT = int(os.getenv("DB_CONNECT_TIMEOUT", "5"))
DATABASE_URL="postgresql://postgres:shaishavroot19@db.vzmbwobdlddxzgqfhnsh.supabase.co:5432/postgres"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# In Django 4.0+, USE_L10N was deprecated; you can omit or leave it if you’re on older Django
# USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# --- Deployment: static & media ---
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'main' / 'static',
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# (already set elsewhere—keep as you have)

# Sessions: keep users signed in longer by default
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_SAVE_EVERY_REQUEST = True  # refresh expiry on activity
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
