from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('about/', views.about, name='about'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('disclaimer/', views.disclaimer, name='disclaimer'),
    path('get-subtopics/', views.get_subtopics, name='get_subtopics'),
    path('practice-questions/', views.practice_questions, name='practice_questions'),
    path('check-answer/', views.check_answer, name='check_answer'),
    path('update-activity/', views.update_activity, name='update_activity'),
    path('question-bank/', views.question_bank, name='question_bank'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('password-reset-request/', views.password_reset_request, name='password_reset_request'),
    path('change-password/', views.change_password, name='change_password'),
    path('user-stats/', views.user_stats, name='user_stats'),
    path('progress/', views.progress_tracker, name='progress_tracker'),
    path('progress/save/', views.save_progress, name='save_progress'),
    path('saved/', views.saved_questions, name='saved_questions'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('staff/user-activity/', views.user_activity_admin, name='user_activity_admin'),
    path('staff/reset-password/', views.staff_reset_password, name='staff_reset_password'),
    path('staff/password-requests/', views.staff_password_requests, name='staff_password_requests'),
    path('staff/theme-access/', views.staff_theme_access, name='staff_theme_access'),
    path('report-bug/', views.report_bug, name='report_bug'),
    path('report-bug/thanks/', views.report_bug_thanks, name='report_bug_thanks'),
    path('staff/bugs/', views.staff_bug_list, name='staff_bug_list'),
    path('staff/bugs/<int:bug_id>/', views.staff_bug_detail, name='staff_bug_detail'),
    path('staff/bugs/<int:bug_id>/status/', views.staff_bug_update_status, name='staff_bug_update_status'),
]
