# Generated by Django 5.1.3 on 2024-11-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100, unique=True)),
                ('session_code', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('paper_code', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('file_question', models.CharField(max_length=255)),
                ('subtopic', models.CharField(max_length=255)),
                ('extracted_text', models.TextField()),
                ('image_base64', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
