# Generated by Django 5.1.3 on 2024-11-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('times_viewed', models.IntegerField(default=0)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_took', models.DurationField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
