# Generated by Django 5.1.3 on 2024-11-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='U1', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
