# Generated by Django 5.1.3 on 2025-08-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0005_remove_useractivity_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("session_code", models.CharField(max_length=100)),
                ("session", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("paper_code", models.CharField(max_length=50)),
                ("variant", models.CharField(max_length=50)),
                ("file_question", models.TextField()),
                ("subtopic", models.CharField(max_length=255)),
                ("extracted_text", models.TextField()),
                ("image_base64", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("school", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solved", models.BooleanField(default=False)),
                ("correct", models.BooleanField(default=False)),
                ("bookmarked", models.BooleanField(default=False)),
                ("starred", models.BooleanField(default=False)),
                ("times_viewed", models.IntegerField(default=0)),
                ("time_started", models.DateTimeField(blank=True, null=True)),
                ("time_took", models.DurationField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.user"
                    ),
                ),
            ],
        ),
    ]
