# Generated by Django 5.1.3 on 2025-08-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="question",
            table="questions",
        ),
    ]
