# Generated by Django 5.1.3 on 2025-08-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_question_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.AlterModelTable(
            name="useractivity",
            table="useractivity",
        ),
    ]
