# Generated by Django 5.1.3 on 2025-08-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_user_table_alter_useractivity_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="useractivity",
            table="user_activity",
        ),
    ]
