# Generated by Django 5.1.3 on 2025-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_bug_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="champion_theme_access",
            field=models.BooleanField(default=False),
        ),
    ]
