# Generated by Django 5.1.3 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="access_mode",
            field=models.CharField(
                choices=[("unlimited", "Unlimited"), ("limited", "Limited")],
                default="unlimited",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="request_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
