# Generated by Django 5.1.3 on 2026-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_questionbanknotice"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE questions ADD COLUMN IF NOT EXISTS image_key TEXT;",
                    reverse_sql="ALTER TABLE questions DROP COLUMN IF EXISTS image_key;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE questions ADD COLUMN IF NOT EXISTS image_url TEXT;",
                    reverse_sql="ALTER TABLE questions DROP COLUMN IF EXISTS image_url;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="question",
                    name="image_key",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="question",
                    name="image_url",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]
