# Generated by Django 5.1.3 on 2026-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_question_image_key_question_image_url"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE users ADD COLUMN IF NOT EXISTS champion_theme VARCHAR(20) DEFAULT 'gold';",
                    reverse_sql="ALTER TABLE users DROP COLUMN IF EXISTS champion_theme;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE users ADD COLUMN IF NOT EXISTS champion_theme_mode BOOLEAN DEFAULT FALSE;",
                    reverse_sql="ALTER TABLE users DROP COLUMN IF EXISTS champion_theme_mode;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE users ADD COLUMN IF NOT EXISTS champion_theme_auto_awarded BOOLEAN DEFAULT FALSE;",
                    reverse_sql="ALTER TABLE users DROP COLUMN IF EXISTS champion_theme_auto_awarded;",
                ),
                migrations.RunSQL(
                    sql="""
                    UPDATE users
                    SET champion_theme = 'gold'
                    WHERE champion_theme IS NULL OR champion_theme = '';
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                    UPDATE users
                    SET champion_theme_mode = FALSE
                    WHERE champion_theme_mode IS NULL;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                    UPDATE users
                    SET champion_theme_auto_awarded = FALSE
                    WHERE champion_theme_auto_awarded IS NULL;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="champion_theme",
                    field=models.CharField(default="gold", max_length=20),
                ),
                migrations.AddField(
                    model_name="user",
                    name="champion_theme_mode",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="user",
                    name="champion_theme_auto_awarded",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
